/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all users with pagination and limit */
        get: operations["UsersController_getAllUsers"];
        put?: never;
        post: operations["UsersController_createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/create-many": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UsersController_createManyUsers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the current user's profile */
        patch: operations["UsersController_updateMe"];
        trace?: never;
    };
    "/users/avatar-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available predefined avatar options */
        get: operations["UsersController_getAvatarOptions"];
        put?: never;
        /** Add a new avatar option (admin only) */
        post: operations["UsersController_createAvatarOption"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/avatar-options/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove an avatar option (admin only) */
        delete: operations["UsersController_removeAvatarOption"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get public profile for a content author or editor */
        get: operations["UsersController_getPublicProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_getUser"];
        put?: never;
        post?: never;
        delete: operations["UsersController_deleteUser"];
        options?: never;
        head?: never;
        patch: operations["UsersController_updateUser"];
        trace?: never;
    };
    "/users/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Select a predefined avatar */
        patch: operations["UsersController_selectAvatar"];
        trace?: never;
    };
    "/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UsersController_changeUserRole"];
        trace?: never;
    };
    "/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List audit log entries (admin only) */
        get: operations["AuditLogController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PostsController_findAll"];
        put?: never;
        /** Create a new post */
        post: operations["PostsController_createPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PostsController_findBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PostsController_findMyPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PostsController_findOne"];
        put?: never;
        post?: never;
        delete: operations["PostsController_remove"];
        options?: never;
        head?: never;
        /** Update a post */
        patch: operations["PostsController_update"];
        trace?: never;
    };
    "/posts/{id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add tags to a post */
        post: operations["PostsController_addTags"];
        /** Remove tags from a post */
        delete: operations["PostsController_removeTags"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all images uploaded for a post */
        get: operations["PostsController_findPostImages"];
        put?: never;
        /** Upload an image for a post */
        post: operations["PostsController_uploadPostImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TagsController_findAllTags"];
        put?: never;
        post: operations["TagsController_createTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["TagsController_deleteTag"];
        options?: never;
        head?: never;
        patch: operations["TagsController_updateTag"];
        trace?: never;
    };
    "/tags/soft/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["TagsController_softDeleteTag"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_refreshTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_verifyEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/google-authentication": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GoogleAuthenticationController_authenticate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta-options/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MetaOptionsController_findOne"];
        put?: never;
        post?: never;
        delete: operations["MetaOptionsController_delete"];
        options?: never;
        head?: never;
        patch: operations["MetaOptionsController_update"];
        trace?: never;
    };
    "/contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ContactController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List published products */
        get: operations["ProductsController_findAll"];
        put?: never;
        /** Create a product (admin only) */
        post: operations["ProductsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a published product by slug */
        get: operations["ProductsController_findBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all products including drafts (admin only) */
        get: operations["ProductsController_findAllAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a published product by id */
        get: operations["ProductsController_findOne"];
        put?: never;
        post?: never;
        /** Soft-delete a product (admin only) */
        delete: operations["ProductsController_remove"];
        options?: never;
        head?: never;
        /** Update a product (admin only) */
        patch: operations["ProductsController_update"];
        trace?: never;
    };
    "/products/{id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload main product image (admin only) */
        post: operations["ProductsController_uploadImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all product types */
        get: operations["ProductTypesController_findAll"];
        put?: never;
        /** Create a product type (admin only) */
        post: operations["ProductTypesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product-types/slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a product type by slug */
        get: operations["ProductTypesController_findBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a product type by id */
        get: operations["ProductTypesController_findOne"];
        put?: never;
        post?: never;
        /** Delete a product type (admin only) */
        delete: operations["ProductTypesController_delete"];
        options?: never;
        head?: never;
        /** Update a product type (admin only) */
        patch: operations["ProductTypesController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateUserDto: {
            /**
             * @description User first name
             * @example Ichigo
             */
            firstName: string;
            /**
             * @description User last name
             * @example Kurosaki
             */
            lastName?: string;
            /**
             * @description User email
             * @example ichigo@bleach.com
             */
            email: string;
            /**
             * @description User password and must contain Minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character
             * @example qwer!@QWER123
             */
            password: string;
        };
        CreateManyUsersDto: {
            users: components["schemas"]["CreateUserDto"][];
        };
        PatchUserProfileDto: {
            /**
             * @description User first name
             * @example Ichigo
             */
            firstName?: string;
            /**
             * @description User last name
             * @example Kurosaki
             */
            lastName?: string;
            /**
             * @description Short plain-text bio (max 500 chars)
             * @example I build things for the web.
             */
            bio?: string | null;
        };
        SelectAvatarDto: {
            /**
             * @description ID of the chosen avatar option from GET /users/avatar-options
             * @example 1
             */
            avatarOptionId: number;
        };
        ChangeUserRoleDto: {
            /** @enum {string} */
            role: "user" | "editor" | "author" | "admin";
        };
        PatchUserDto: {
            /**
             * @description User first name
             * @example Ichigo
             */
            firstName?: string;
            /**
             * @description User last name
             * @example Kurosaki
             */
            lastName?: string;
            /**
             * @description User email
             * @example ichigo@bleach.com
             */
            email?: string;
            /**
             * @description User password and must contain Minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character
             * @example qwer!@QWER123
             */
            password?: string;
        };
        CreatePostMetaOptionsDto: {
            /**
             * @description The meta value is a JSON string
             * @example { "village": "Konoha", "clan": "Uzumaki" }
             */
            metaValue: string;
        };
        CreatePostDto: {
            /**
             * @description The title of the post
             * @example My first post title
             */
            title?: string;
            /**
             * @description Possible values: post, page, story, series
             * @example post
             * @enum {string}
             */
            postType: "post" | "page" | "story" | "series";
            /**
             * @description The slug of the post
             * @example my-first-post
             */
            slug?: string;
            /**
             * @description Possible values: draft, scheduled, review, published
             * @example published
             * @enum {string}
             */
            status?: "draft" | "scheduled" | "review" | "published";
            /**
             * @description The content of the post
             * @example This is the content of my first post
             */
            content?: string;
            /**
             * @description Serialized JSON object
             * @example {
             *       "village": "Konoha",
             *       "clan": "Uzumaki"
             *     }
             */
            schema?: string;
            /**
             * @description The URL of the featured image for the post
             * @example https://example.com/featured-image.jpg
             */
            featuredImage?: string;
            /**
             * Format: date-time
             * @description The date and time when the post will be published
             * @example 2023-05-29T12:00:00.000Z
             */
            publishOn?: string;
            /**
             * @description The IDs of the tags associated with the post
             * @example [
             *       1,
             *       2,
             *       3
             *     ]
             */
            tags?: string[];
            /** @description The meta options for the post */
            metaOptions?: components["schemas"]["CreatePostMetaOptionsDto"];
        };
        PatchPostDto: {
            /**
             * @description The title of the post
             * @example My first post title
             */
            title?: string;
            /**
             * @description Possible values: post, page, story, series
             * @example post
             * @enum {string}
             */
            postType?: "post" | "page" | "story" | "series";
            /**
             * @description The slug of the post
             * @example my-first-post
             */
            slug?: string;
            /**
             * @description Possible values: draft, scheduled, review, published
             * @example published
             * @enum {string}
             */
            status?: "draft" | "scheduled" | "review" | "published";
            /**
             * @description The content of the post
             * @example This is the content of my first post
             */
            content?: string;
            /**
             * @description Serialized JSON object
             * @example {
             *       "village": "Konoha",
             *       "clan": "Uzumaki"
             *     }
             */
            schema?: string;
            /**
             * @description The URL of the featured image for the post
             * @example https://example.com/featured-image.jpg
             */
            featuredImage?: string;
            /**
             * Format: date-time
             * @description The date and time when the post will be published
             * @example 2023-05-29T12:00:00.000Z
             */
            publishOn?: string;
            /**
             * @description The IDs of the tags associated with the post
             * @example [
             *       1,
             *       2,
             *       3
             *     ]
             */
            tags?: string[];
            /** @description The meta options for the post */
            metaOptions?: components["schemas"]["CreatePostMetaOptionsDto"];
        };
        PostTagsDto: {
            tagIds: number[];
        };
        CreateTagDto: {
            name: string;
            slug: string;
            description?: string;
            schema?: string;
            featuredImage?: string;
        };
        UpdateTagDto: {
            name?: string;
            slug?: string;
            description?: string;
            schema?: string;
            featuredImage?: string;
        };
        SignInDto: {
            /** @example user@example.com */
            email: string;
            password: string;
        };
        RefreshTokenDto: {
            /** @description Refresh token (mobile clients only — browser clients use the HttpOnly cookie) */
            refreshToken?: string;
        };
        ResendVerificationDto: {
            /** @example user@example.com */
            email: string;
        };
        ForgotPasswordDto: {
            /** @example user@example.com */
            email: string;
        };
        ResetPasswordDto: {
            /** @description Password reset token from the email link */
            token: string;
            newPassword: string;
        };
        ChangePasswordDto: {
            currentPassword: string;
            newPassword: string;
        };
        GoogleTokenDto: {
            /** @description Google ID token obtained from the client-side Google Sign-In flow */
            token: string;
        };
        UpdateMetaOptionDto: {
            /**
             * @description The meta value is a JSON string
             * @example { "village": "Konoha", "clan": "Uzumaki" }
             */
            metaValue?: string;
        };
        CreateContactDto: {
            /** @example Jane Doe */
            name: string;
            /** @example jane@example.com */
            email: string;
            /** @example Hiring inquiry */
            subject: string;
            /** @example Hello, I wanted to reach out... */
            message: string;
        };
        FilterableFieldDto: {
            /**
             * @description Key matching a product spec
             * @example tempRange
             */
            key: string;
            /**
             * @description Label shown in the filter UI
             * @example Temperature Range
             */
            label: string;
            /**
             * @description Renders a range for number, dropdown for enum, text for string
             * @enum {string}
             */
            type: "number" | "enum" | "string";
            /**
             * @description Unit suffix for display
             * @example °C
             */
            unit?: string;
            /**
             * @description Allowed values when type is enum
             * @example [
             *       "Inconel 600",
             *       "Stainless 316"
             *     ]
             */
            options?: string[];
        };
        ProductType: {
            /** @example 1 */
            id: number;
            /** @example Thermocouple */
            name: string;
            /** @example thermocouple */
            slug: string;
            /** @description Filter facets the frontend renders for this type */
            filterableFields?: components["schemas"]["FilterableFieldDto"][] | null;
            /**
             * @description Number of published products in this type
             * @example 24
             */
            productCount?: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Product: {
            /** @example 1 */
            id: number;
            /** @example Type K Thermocouple */
            name: string;
            /** @example type-k-thermocouple */
            slug: string;
            /** @example TC-K-1260-IC */
            sku?: string | null;
            /** @example High-accuracy thermocouple for industrial use */
            shortDescription: string;
            description?: string | null;
            imageUrl?: string | null;
            images?: string[] | null;
            /**
             * @description Type-specific attribute values; keys match the type filterableFields
             * @example {
             *       "tempRange": 1260,
             *       "sheathMaterial": "Inconel 600"
             *     }
             */
            specs?: {
                [key: string]: unknown;
            } | null;
            /** @example true */
            isPublished: boolean;
            productType: components["schemas"]["ProductType"];
            /** @example 1 */
            productTypeId: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            deletedAt?: string | null;
        };
        CreateProductDto: {
            /**
             * @description Product display name
             * @example Type K Thermocouple
             */
            name: string;
            /**
             * @description URL slug, unique across all products
             * @example type-k-thermocouple
             */
            slug: string;
            /**
             * @description ID of the product type this product belongs to
             * @example 1
             */
            productTypeId: number;
            /**
             * @description Short description for list cards and search results
             * @example High-accuracy thermocouple for industrial use
             */
            shortDescription: string;
            /** @description Full detail body shown on the product page */
            description?: Record<string, never>;
            /**
             * @description Vendor or internal SKU code
             * @example TC-K-1260-IC
             */
            sku?: Record<string, never>;
            /**
             * @description Main Cloudinary image URL
             * @example https://res.cloudinary.com/demo/image/upload/v1/products/tc-k.jpg
             */
            imageUrl?: Record<string, never>;
            /** @description Gallery of additional Cloudinary URLs */
            images?: Record<string, never>;
            /**
             * @description Type-specific attribute values — keys must match the product type's filterableFields
             * @example {
             *       "tempRange": 1260,
             *       "accuracy": 0.75,
             *       "sheathMaterial": "Inconel 600"
             *     }
             */
            specs?: Record<string, never>;
            /**
             * @description Publish the product immediately (defaults to false)
             * @default false
             */
            isPublished: boolean;
        };
        UpdateProductDto: {
            /**
             * @description Product display name
             * @example Type K Thermocouple
             */
            name?: string;
            /**
             * @description URL slug, unique across all products
             * @example type-k-thermocouple
             */
            slug?: string;
            /**
             * @description ID of the product type this product belongs to
             * @example 1
             */
            productTypeId?: number;
            /**
             * @description Short description for list cards and search results
             * @example High-accuracy thermocouple for industrial use
             */
            shortDescription?: string;
            /** @description Full detail body shown on the product page */
            description?: Record<string, never>;
            /**
             * @description Vendor or internal SKU code
             * @example TC-K-1260-IC
             */
            sku?: Record<string, never>;
            /**
             * @description Main Cloudinary image URL
             * @example https://res.cloudinary.com/demo/image/upload/v1/products/tc-k.jpg
             */
            imageUrl?: Record<string, never>;
            /** @description Gallery of additional Cloudinary URLs */
            images?: Record<string, never>;
            /**
             * @description Type-specific attribute values — keys must match the product type's filterableFields
             * @example {
             *       "tempRange": 1260,
             *       "accuracy": 0.75,
             *       "sheathMaterial": "Inconel 600"
             *     }
             */
            specs?: Record<string, never>;
            /**
             * @description Publish the product immediately (defaults to false)
             * @default false
             */
            isPublished: boolean;
        };
        DeleteResultDto: {
            /**
             * @description Whether the record was deleted
             * @example true
             */
            deleted: boolean;
            /**
             * @description ID of the deleted record
             * @example 1
             */
            id: number;
        };
        CreateProductTypeDto: {
            /**
             * @description Human-readable product type name
             * @example Thermocouple
             */
            name: string;
            /**
             * @description URL-safe slug, unique across types
             * @example thermocouple
             */
            slug: string;
            /**
             * @description Filter facets shown in the product filter UI for this type
             * @example [
             *       {
             *         "key": "tempRange",
             *         "label": "Temperature Range",
             *         "type": "number",
             *         "unit": "°C"
             *       },
             *       {
             *         "key": "sheathMaterial",
             *         "label": "Sheath Material",
             *         "type": "enum",
             *         "options": [
             *           "Inconel 600",
             *           "Stainless 316"
             *         ]
             *       }
             *     ]
             */
            filterableFields?: Record<string, never>;
        };
        UpdateProductTypeDto: {
            /**
             * @description Human-readable product type name
             * @example Thermocouple
             */
            name?: string;
            /**
             * @description URL-safe slug, unique across types
             * @example thermocouple
             */
            slug?: string;
            /**
             * @description Filter facets shown in the product filter UI for this type
             * @example [
             *       {
             *         "key": "tempRange",
             *         "label": "Temperature Range",
             *         "type": "number",
             *         "unit": "°C"
             *       },
             *       {
             *         "key": "sheathMaterial",
             *         "label": "Sheath Material",
             *         "type": "enum",
             *         "options": [
             *           "Inconel 600",
             *           "Stainless 316"
             *         ]
             *       }
             *     ]
             */
            filterableFields?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
    };
    UsersController_getAllUsers: {
        parameters: {
            query?: {
                /** @description Number of items per page */
                limit?: number;
                /** @description Page number to return (1-based) */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_createManyUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateManyUsersDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchUserProfileDto"];
            };
        };
        responses: {
            /** @description Profile updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getAvatarOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of avatar options */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_createAvatarOption: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Avatar option created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_removeAvatarOption: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Avatar option removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Option not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getPublicProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found or user is not a content author */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_selectAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectAvatarDto"];
            };
        };
        responses: {
            /** @description Avatar updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown avatar option id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_changeUserRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeUserRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuditLogController_findAll: {
        parameters: {
            query?: {
                /** @description Number of items per page */
                limit?: number;
                /** @description Page number to return (1-based) */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PostsController_findAll: {
        parameters: {
            query?: {
                /** @description Keyword search across title and content */
                q?: string;
                /** @description Number of items per page */
                limit?: number;
                /** @description Page number to return (1-based) */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PostsController_createPost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePostDto"];
            };
        };
        responses: {
            /** @description The post has been successfully created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PostsController_findBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PostsController_findMyPosts: {
        parameters: {
            query?: {
                /** @description Keyword search across title and content */
                q?: string;
                /** @description Number of items per page */
                limit?: number;
                /** @description Page number to return (1-based) */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PostsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PostsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PostsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchPostDto"];
            };
        };
        responses: {
            /** @description The post has been successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PostsController_addTags: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostTagsDto"];
            };
        };
        responses: {
            /** @description Tags added successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid tag IDs */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not the post author */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Post not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PostsController_removeTags: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostTagsDto"];
            };
        };
        responses: {
            /** @description Tags removed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not the post author */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Post not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PostsController_findPostImages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of UploadFile records */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not the post author */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Post not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PostsController_uploadPostImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image uploaded successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid file */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not the post author */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Post not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagsController_findAllTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagsController_createTag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTagDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagsController_deleteTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagsController_updateTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTagDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagsController_softDeleteTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refreshTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_signOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_verifyEmail: {
        parameters: {
            query: {
                /** @description Email verification token from the verification email link */
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_resendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendVerificationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GoogleAuthenticationController_authenticate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleTokenDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MetaOptionsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MetaOptionsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MetaOptionsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMetaOptionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ContactController_submit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContactDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_findAll: {
        parameters: {
            query?: {
                /** @description Number of items per page */
                limit?: number;
                /** @description Page number to return (1-based) */
                page?: number;
                /** @description Filter by product type ID */
                productTypeId?: number;
                /** @description Filter by product type slug — alternative to productTypeId so a per-type page can load without first resolving the id. productTypeId wins if both are sent. */
                typeSlug?: string;
                /** @description Keyword search across product name and short description */
                q?: string;
                /** @description Sort order. newest (default) and oldest sort by creation date; name sorts A–Z. */
                sort?: "newest" | "oldest" | "name";
                /** @description Spec filters sent as bracket-nested params (parsed by the 'extended' query parser). Enum/string facets take an exact value; number facets take an exact value or a [min]/[max] range. Keys must match the type's filterableFields, so a type context (productTypeId or typeSlug) is required. Example: specs[sheathMaterial]=Inconel 600&specs[tempRange][min]=1000&specs[tempRange][max]=1600. */
                specs?: {
                    [key: string]: unknown;
                };
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        apiVersion?: string;
                        data?: {
                            data?: components["schemas"]["Product"][];
                            meta?: {
                                itemsPerPage?: number;
                                totalItems?: number;
                                currentPage?: number;
                                totalPages?: number;
                                hasNextPage?: boolean;
                                hasPrevPage?: boolean;
                            };
                            links?: {
                                first?: string;
                                last?: string;
                                current?: string;
                                next?: string;
                                prev?: string;
                            };
                        };
                    };
                };
            };
        };
    };
    ProductsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductDto"];
            };
        };
        responses: {
            /** @description Product created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        apiVersion?: string;
                        data?: components["schemas"]["Product"];
                    };
                };
            };
            /** @description Slug or SKU already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_findBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        apiVersion?: string;
                        data?: components["schemas"]["Product"];
                    };
                };
            };
            /** @description Product not found or not published */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_findAllAdmin: {
        parameters: {
            query?: {
                /** @description Number of items per page */
                limit?: number;
                /** @description Page number to return (1-based) */
                page?: number;
                /** @description Filter by product type ID */
                productTypeId?: number;
                /** @description Filter by product type slug — alternative to productTypeId so a per-type page can load without first resolving the id. productTypeId wins if both are sent. */
                typeSlug?: string;
                /** @description Keyword search across product name and short description */
                q?: string;
                /** @description Sort order. newest (default) and oldest sort by creation date; name sorts A–Z. */
                sort?: "newest" | "oldest" | "name";
                /** @description Spec filters sent as bracket-nested params (parsed by the 'extended' query parser). Enum/string facets take an exact value; number facets take an exact value or a [min]/[max] range. Keys must match the type's filterableFields, so a type context (productTypeId or typeSlug) is required. Example: specs[sheathMaterial]=Inconel 600&specs[tempRange][min]=1000&specs[tempRange][max]=1600. */
                specs?: {
                    [key: string]: unknown;
                };
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        apiVersion?: string;
                        data?: {
                            data?: components["schemas"]["Product"][];
                            meta?: {
                                itemsPerPage?: number;
                                totalItems?: number;
                                currentPage?: number;
                                totalPages?: number;
                                hasNextPage?: boolean;
                                hasPrevPage?: boolean;
                            };
                            links?: {
                                first?: string;
                                last?: string;
                                current?: string;
                                next?: string;
                                prev?: string;
                            };
                        };
                    };
                };
            };
        };
    };
    ProductsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        apiVersion?: string;
                        data?: components["schemas"]["Product"];
                    };
                };
            };
            /** @description Product not found or not published */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        apiVersion?: string;
                        data?: components["schemas"]["DeleteResultDto"];
                    };
                };
            };
        };
    };
    ProductsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        apiVersion?: string;
                        data?: components["schemas"]["Product"];
                    };
                };
            };
            /** @description Slug or SKU already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_uploadImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image uploaded; product returned with updated imageUrl */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        apiVersion?: string;
                        data?: components["schemas"]["Product"];
                    };
                };
            };
            /** @description Invalid file type or size */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductTypesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        apiVersion?: string;
                        data?: components["schemas"]["ProductType"][];
                    };
                };
            };
        };
    };
    ProductTypesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductTypeDto"];
            };
        };
        responses: {
            /** @description Product type created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        apiVersion?: string;
                        data?: components["schemas"]["ProductType"];
                    };
                };
            };
            /** @description Name or slug already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductTypesController_findBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        apiVersion?: string;
                        data?: components["schemas"]["ProductType"];
                    };
                };
            };
            /** @description Product type not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductTypesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        apiVersion?: string;
                        data?: components["schemas"]["ProductType"];
                    };
                };
            };
            /** @description Product type not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductTypesController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        apiVersion?: string;
                        data?: components["schemas"]["DeleteResultDto"];
                    };
                };
            };
            /** @description Products still reference this type */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductTypesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductTypeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        apiVersion?: string;
                        data?: components["schemas"]["ProductType"];
                    };
                };
            };
            /** @description Name or slug already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
